name: ezzewash
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- State Management ---
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  equatable: ^2.0.5

  # --- Navigation ---
  go_router: ^17.1.0

  # --- Supabase ---
  supabase_flutter: ^2.5.6

  # --- Dependency Injection ---
  get_it: ^9.2.1

  # --- Network & Storage ---
  dio: ^5.4.3+1
  flutter_stripe: ^12.4.0
  http: ^1.2.1
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.0.0

  # --- UI ---
  google_fonts: ^8.0.2
  iconsax: ^0.0.8
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.1

  # --- Utilities ---
  intl: ^0.20.2
  uuid: ^4.4.2
  dartz: ^0.10.1

  # --- Functional Programming ---
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.14.2
  device_info_plus: ^12.3.0
  geolocator: ^14.0.2
  geocoding: ^2.1.1
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.6.0
  onesignal_flutter: ^5.4.6
  flutter_local_notifications: ^21.0.0
  firebase_messaging: ^16.1.3
  flutter_native_splash: ^2.4.7
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animation/
    - assets/service_picture/
    - assets/services/
    - assets/images/
    - assets/logo/

flutter_native_splash:
  # ─── Light Theme Config ──────────────────────────────────────────
  color: "#42a5f5"
  image: "assets/logo/logo.png"

  # ─── Android 12+ Specific Config ─────────────────────────────────
  android_12:
    color: "#42a5f5"
    # ─── Dark Theme Override (Android 12+) ─────────────────────────
    color_dark: "#042a49"

  # ─── General Dark Theme (Older Android/iOS) ──────────────────────
  color_dark: "#042a49"

  fullscreen: true